### ISSUE TITLE
Create breakpoints to hide images on homepage

### ISSUE THREAD

**Issue by CalvinFronda** [omou-org/omou-org.github.io#9]
Material Ui gives us easy to use breakpoints to hide elements when the screen size changes.

To complete this ticket,
1.  use the "display" property to hide images on small screens and below. 

<img width="676" alt="Screen Shot 2020-04-15 at 5 31 33 PM" src="https://user-images.githubusercontent.com/40410706/79401808-f7c7fc80-7f3e-11ea-99f5-c3cd82d1fd65.png">

Resources: 
https://material-ui.com/system/display/#display

**Comment by rgedwill** [comment]
Working on it today
